version: "1.0"
info:
  model: int-scaffold
packages:
- name: AdpExternalProject
  gitServerName: vmadprhel2Adp
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
